mesh_dir: ar4_mk3
j4_limit: !degrees 180.0
j6_limit: !degrees 180.0
l6_length: 0.041
linear_track_width:  0.3
linear_track_length: 0.6
linear_track_height: 0.041
linear_plate_width:  0.15
linear_plate_length: 0.3
linear_plate_height: 0.004
linear_bearing_spacer: 0.048

j1_limit_min: !degrees -170
j2_limit_min: !degrees -42
j3_limit_min: !degrees -89
j4_limit_min: !degrees -180
j5_limit_min: !degrees -105
j6_limit_min: !degrees -180

j1_limit_max: !degrees 170
j2_limit_max: !degrees 90
j3_limit_max: !degrees 52
j4_limit_max: !degrees 180
j5_limit_max: !degrees 105
j6_limit_max: !degrees 180