mesh_dir: ar4_mk3
j4_limit: !degrees 180.0
j6_limit: !degrees 180.0
l6_length: 0.041
linear_track_width: 0.3
linear_track_length: 0.6
linear_track_height: 0.041
linear_plate_width:  0.15
linear_plate_length: 0.3
linear_plate_height: 0.004
